---
- name: install package
  yum:
    name: "{{ apache_service_name }}"
    state: installed

- name: start and enable httpd
  systemd:
    name: "{{ apache_service_name }}"
    state: "{{service_start_state}}"
    enabled: yes

- name: copy index.html file to the remote hosts
  copy:
    src: "../{{ html_page_src }}"
    dest: "{{ html_page_dest }}"
    remote_src: true
