---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
- name: install package
  apt:
    name: "{{ apache_service_name }}"
    update_cache: true
    state: latest

- name: start and enable httpd
  systemd:
    name: "{{ apache_service_name }}"
    state: "{{service_start_state}}"
    enabled: yes


- name: copy index.html file to the remote hosts
  copy:
    src: "{{ html_page_src }}"
    dest: "{{ html_page_dest }}"
    remote_src: true
